licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "threads",
    srcs = glob(["**/*.cc"]),
    hdrs = glob(["**/*.h"]),
    deps = ["//mediapipe/piano24/rtmidi:rtmidi"]
)
